# General
site_name: Shippable Documentation
repo_url: https://github.com/lekhab

# Paths
docs_dir: sources
theme_dir: theme/shippable

# Pages
pages:
  - [index.md, Getting Started, Shippable]
  - [quick_start_build.md, Getting Started, 'Quick Start: Run your first build']
  - [quick_start_formations.md, Getting Started, 'Quick Start: Set up your first Formation']

  - [overview_ci.md, Shippable CI, Overview]
  - [user_guide_ci.md, Shippable CI, User Guide]
  - [yml_reference.md, Shippable CI, YML reference]
  - [languages/index.md, Shippable CI, Language help]
  - [languages/images.md, Shippable CI, Build images]

  - [overview_formations.md, Shippable Formations, Overview]
  - [user_guide_formations.md, Shippable Formations, User Guide]

  - [deployment/index.md, Deployment, Overview]
  - [deployment/heroku.md, Deployment, Heroku]
  - [deployment/beanstalk.md, Deployment, Amazon Elastic Beanstalk]
  - [deployment/opswork.md, Deployment, AWS OpsWorks]
  - [deployment/appengine.md, Deployment, Google App Engine]
  - [deployment/openshift.md, Deployment, Red Hat OpenShift]
  - [deployment/digitalocean.md, Deployment, DigitalOcean]
  - [deployment/codedeploy.md, Deployment, AWS CodeDeploy]

  - [docker_registries.md, Registry, Overview]
  - [docker.md, Registry, Docker Hub]
  - [gcr.md, Registry, Google Container Registry]

  - [api.md, Reference, API]
  - [shippable_samples.md, Reference, Samples]
  - [faq.md, Reference, FAQ]

